CTodo/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace Ctodo.Models;

public class Category
{
    [Key] public Guid CategoryId { get; set; }
    [Required] public string? Name { get; set; }
}

CTodo/Models/Todo.cs
using System.ComponentModel.DataAnnotations;

namespace Ctodo.Models;

public class Todo
{
    [Key] public Guid TodoId { get; set; }
    [Required] public string Title { get; set; }
    public bool IsCompleted { get; set; } = false;
    public DateTime? DueDate { get; set; }
    [MaxLength(50)] public string Priority { get; set; } = "Low";
    public List<Category> Categories { get; set; } = new List<Category>();
}

CTodo/Models/ViewModel/CategoryIndexViewModel.cs
using CTodo.Providers;

namespace Ctodo.Models.ViewModel;

public class CategoryIndexViewModel
{
    public List<Category> Categories { get; set; }
    public CategoryViewModel CategoryCreate { get; set; }
}

CTodo/Models/ViewModel/CategoryViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Ctodo.Models.ViewModel;

public class CategoryViewModel
{
    [Required(ErrorMessage = "Category name is required!")]
    public string Name { get; set; }
}

CTodo/Models/ViewModel/TodoIndexViewModel.cs
namespace Ctodo.Models.ViewModel;

public class TodoIndexViewModel
{
    public List<Todo> Todos { get; set; }
    public List<Category> Categories { get; set; }
    public TodoItemViewModel? TodoItemViewModel { get; set; }
}

CTodo/Models/ViewModel/TodoItemViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Ctodo.Models.ViewModel;

public class TodoItemViewModel
{
    [Required(ErrorMessage = "Title is required!")]
    public string Title { get; set; }

    [Required(ErrorMessage = "Category is required!")]
    public Guid Category { get; set; }

    public string Priority { get; set; }
    public DateTime? DueDate { get; set; }
}

CTodo/Controllers/CategoryController.cs
using Ctodo.Models.ViewModel;
using CTodo.Options;
using CTodo.Repositories.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Ctodo.Controllers;

public class CategoryController : Controller
{
    private readonly ICategoryRepository _categoryRepository;
    private readonly IOptionsMonitor<StorageOptions> _storageOptions;

    public CategoryController(ICategoryRepository categoryRepository, IOptionsMonitor<StorageOptions> storageOptions)
    {
        _categoryRepository = categoryRepository;
        _storageOptions = storageOptions;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var categories = await _categoryRepository.Categories();
        var storageOptions = _storageOptions.CurrentValue;
        ViewBag.CurrentStorageType = storageOptions.StorageType;

        var categoryIndexViewModel = new CategoryIndexViewModel()
        {
            Categories = categories.ToList()
        };

        return View(categoryIndexViewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Create(CategoryViewModel model)
    {
        if (!ModelState.IsValid) return RedirectToAction("Index");

        await _categoryRepository.Create(model);

        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> Delete(Guid categoryId)
    {
        await _categoryRepository.DeleteById(categoryId);

        return RedirectToAction("Index");
    }
}

CTodo/Controllers/ConfigController.cs
using CTodo.Providers;
using Microsoft.AspNetCore.Mvc;

namespace Ctodo.Controllers;

public class ConfigController : Controller
{
    private readonly StorageTypeProvider _storageTypeProvider;

    public ConfigController(StorageTypeProvider storageTypeProvider)
    {
        _storageTypeProvider = storageTypeProvider;
    }

    [HttpPost]
    public IActionResult SetStorageType(string StorageType)
    {
        _storageTypeProvider.UpdateStorageType(StorageType.ToLower());

        return RedirectToActionPermanent("Index", "Todo");
    }
}

CTodo/Controllers/GraphQLController.cs
using GraphQL;
using GraphQL.Types;
using Microsoft.AspNetCore.Mvc;
using CTodo.GraphQL.GraphQLQueries;

namespace Ctodo.Controllers;

[Route("graphql")]
[ApiController]
public class GraphQLController : Controller
{
    private readonly IServiceProvider _serviceProvider;

    public GraphQLController(IServiceProvider serviceProvider)
    {
        _serviceProvider = serviceProvider;
    }

    [HttpPost]
    public async Task<IActionResult> Post([FromBody] GraphQLQuery query)
    {
        if (query == null)
        {
            throw new ArgumentNullException(nameof(query));
        }

        using (var scope = _serviceProvider.CreateScope())
        {
            var schema = scope.ServiceProvider.GetRequiredService<ISchema>();
            var executer = scope.ServiceProvider.GetRequiredService<IDocumentExecuter>();

            var inputs = query.Variables != null ? new Inputs(query.Variables) : Inputs.Empty;
            var executionOptions = new ExecutionOptions
            {
                Schema = schema,
                Query = query.Query,
                Root = inputs
            };

            var result = await executer.ExecuteAsync(executionOptions);

            if (result.Errors?.Count > 0)
            {
                return BadRequest(result);
            }

            return Ok(result);
        }
    }
}

CTodo/Controllers/TodoController.cs
using Ctodo.Models.ViewModel;
using CTodo.Options;
using CTodo.Repositories.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Ctodo.Controllers;

public class TodoController : Controller
{
    private readonly ITodoRepository _todoRepository;
    private readonly ICategoryRepository _categoryRepository;
    private readonly IOptionsMonitor<StorageOptions> _storageOptions;

    public TodoController(ITodoRepository todoRepository, ICategoryRepository categoryRepository,
        IOptionsMonitor<StorageOptions> storageOptions)
    {
        _todoRepository = todoRepository;
        _categoryRepository = categoryRepository;
        _storageOptions = storageOptions;
    }

    [HttpGet]
    public async Task<ActionResult> Index()
    {
        var todos = await _todoRepository.Todos();
        var categories = await _categoryRepository.Categories();
        var storageOptions = _storageOptions.CurrentValue;
        ViewBag.CurrentStorageType = storageOptions.StorageType;

        var todoIndex = new TodoIndexViewModel()
        {
            Todos = todos.ToList(),
            Categories = categories.ToList(),
        };

        return View(todoIndex);
    }

    [HttpPost]
    public async Task<IActionResult> Create(TodoItemViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return RedirectToActionPermanent("Index");
        }

        await _todoRepository.Create(model);

        return RedirectToActionPermanent("Index");
    }

    [HttpPost]
    public async Task<IActionResult> ToggleTodoCompleted(Guid TodoId, bool IsCompleted)
    {
        await _todoRepository.ToggleCompleted(TodoId, IsCompleted);

        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> DeleteTodo(Guid TodoId)
    {
        await _todoRepository.DeleteById(TodoId);

        return RedirectToAction("Index");
    }
}

CTodo/Views/Category/Create.cshtml
@using Ctodo.Models.ViewModel;

@model CategoryViewModel

<div class="mt-5 ">
    <h2 class="text-center">Create category</h2>
    <div class="d-flex justify-content-center">
        <form class="mt-2" style="max-width: 450px; width: 100%" asp-controller="Category" asp-action="Create" method="post">
            <div class="my-3">
                <label for="Name" class="form-label">Category name</label>
                <input type="text" class="form-control" id="Name" name="Name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mt-3 d-flex justify-content-center">
                <button id="create-category" class="btn btn-outline-success" type="submit">Send</button>
            </div>
        </form>
    </div>
</div>

CTodo/Views/Category/Index.cshtml
@using Microsoft.IdentityModel.Tokens
@using Ctodo.Models.ViewModel

@model CategoryIndexViewModel

@{
    ViewData["Title"] = "Categories";
}

<div>
    @await Html.PartialAsync("Create", Model.CategoryCreate)
    <h2 class="mt-4 text-center">Categories</h2>
    <div class="mt-3">
        <div class="d-flex justify-content-center">
            <div class="mt-3" style="max-width: 450px; width: 100%">
                @{
                    if (!Model.Categories.IsNullOrEmpty())
                    {
                        foreach (var category in Model.Categories)
                        {
                            <div class="my-2 px-2 py-1 d-flex justify-content-between border border-1 border-secondary rounded">
                                <div>
                                    @category.Name
                                </div>
                                <div>
                                    <form method="post" asp-action="Delete">
                                        <input name="categoryId" value="@category.CategoryId" type="hidden"/>
                                        <button class="btn btn-outline-danger" type="submit">Delete</button>
                                    </form>
                                </div>
                            </div>
                        }
                    }
                    else
                    {
                        <div>
                            <h3 class="text-center">No categories created yet</h3>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>

CTodo/Views/Shared/HeaderPartial.cshtml
@{
    var currentStorageType = ViewBag.CurrentStorageType as string;
}

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Todo" asp-action="Index">Ctodo</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Todo" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Todo" asp-action="Index">Todo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                    </li>
                </ul>
            </div>
            <form class="d-flex gap-4" asp-controller="Config" asp-action="SetStorageType">
                <div>
                    <select class="form-select" name="StorageType" id="Storage">
                        <option value="database" selected="@(currentStorageType == "database")">Database</option>
                        <option value="xml" selected="@(currentStorageType == "xml")">Xml File</option>
                    </select>
                </div>
                <div>
                    <button class="btn btn-outline-primary" type="submit">Change</button>
                </div>
            </form>
        </div>
    </nav>
</header>

CTodo/Views/Shared/MetatagsPartial.cshtml
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Ctodo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Ctodo.styles.css" asp-append-version="true"/>
</head>

CTodo/Views/Shared/ScriptsPartial.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

CTodo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
@await Html.PartialAsync("MetatagsPartial")
<body>
@await Html.PartialAsync("HeaderPartial")
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
@await Html.PartialAsync("ScriptsPartial")
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CTodo/Views/Todo/Create.cshtml
@using Ctodo.Models.ViewModel;

@model Tuple<List<Category>, TodoItemViewModel>

<div class="d-flex justify-content-center">
    <form class="mt-3 row" style="max-width: 450px; width: 100%" asp-action="Create" asp-controller="Todo" method="post">
        <h2 class="mb-3 text-center">New Todo</h2>
        <div class="col">
            <div class="mb-3">
                <label for="Title" class="form-label">Title</label>
                <input type="text" class="form-control" id="Title" name="Title">
                <span asp-validation-for="Item2.Title" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Category" class="form-label">Category</label>
                <select class="form-select" name="Category" id="Category">
                    @{
                        foreach (var category in Model.Item1)
                        {
                            <option value="@category.CategoryId">@category.Name</option>
                        }
                    }
                </select>
                <span asp-validation-for="Item2.Category" class="text-danger"></span>
            </div>
        </div>
        <div class="col">
            <div class="mb-3">
                <label for="Priority" class="form-label">Priority</label>
                <select class="form-select" name="Priority" id="Priority">
                    <option value="Low">Low</option>
                    <option value="Medium">Medium</option>
                    <option value="High">High</option>
                </select>
                <span asp-validation-for="Item2.Priority" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="DueDate" class="form-label">Due date</label>
                <input type="date" class="form-control" id="DueDate" name="DueDate"/>
                <span asp-validation-for="Item2.DueDate" class="text-danger"></span>
            </div>
        </div>
        <div class="d-flex justify-content-end">
            <button id="create-todo" class="btn btn-outline-success" type="submit" disabled>Send</button>
        </div>
    </form>
</div>

CTodo/Views/Todo/Index.cshtml
@using Microsoft.IdentityModel.Tokens
@using Ctodo.Models.ViewModel
@model TodoIndexViewModel

@{
    ViewData["Title"] = "Todos";
}

<div>
    @await Html.PartialAsync("Create", new Tuple<List<Category>, TodoItemViewModel>(@Model.Categories, Model.TodoItemViewModel))
    <div class="mt-5 d-flex flex-column align-items-center">
        @{
            if (!Model.Todos.IsNullOrEmpty())
            {
                foreach (var todo in Model.Todos)
                {
                    <div class="my-3 mx-1 col" style="max-width: 600px; width: 100%">
                        <div class="card d-flex flex-row">
                            <div class="card-body">
                                <h5 class="card-title">@todo.Title</h5>
                                <p class="card-text">Priority: @todo.Priority</p>
                                @if (todo.DueDate.HasValue)
                                {
                                    <p class="card-text">Due Date: @todo.DueDate.Value.ToShortDateString()</p>
                                }
                                <div class="form-check">
                                    <form id="formToggleTodoCompleted-@todo.TodoId" asp-action="ToggleTodoCompleted" asp-controller="Todo" method="post">
                                        <input class="form-check-input" type="checkbox" id="todo-@todo.TodoId" name="IsCompleted" value="@((!todo.IsCompleted).ToString().ToLower())" checked="@(todo.IsCompleted)" onclick="handleToggleTodoCompleted('@todo.TodoId')"/>
                                        <input type="hidden" name="TodoId" value="@todo.TodoId"/>
                                    </form>
                                    <label class="form-check-label @(todo.IsCompleted ? "text-success" : "text-warning")" for="todo-@todo.TodoId">
                                        Completed
                                    </label>
                                </div>
                                <div class="mt-2">
                                    @{
                                        if (!todo.Categories.IsNullOrEmpty())
                                        {
                                            foreach (var category in todo.Categories.ToList())
                                            {
                                                <p class="lead m-0 text-primary">Category: @category.Name</p>
                                            }
                                        }
                                    }
                                </div>
                            </div>
                            <div class="p-2 d-flex justify-content-end">
                                <div>
                                    <form asp-controller="Todo" asp-action="DeleteTodo" method="post">
                                        <button class="btn btn-outline-danger" type="submit" name="TodoId" value="@todo.TodoId">Delete</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                }

                <hr class="mt-5"/>
            }
            else
            {
                <h3>No task has been created yet!</h3>
            }
        }
    </div>
</div>